### ISSUE TITLE
録画済み(録画中含む)TSをTvtPlayで再生すると落ちる

### ISSUE THREAD

**Issue by come25136** [noriokun4649/TVTComment#55]
すぐ落ちるTSもあれば数秒再生できるTSもあり、数秒再生できる場合はコメントが流れる事もある
TVTCommentバージョンは恐らくv2.0.1

```
Application: TvtComment.exe
CoreCLR Version: 5.0.1021.41214
.NET Version: 5.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: Cannot call this method on current state. Current state is 'Disposed'
   at TVTComment.Model.IPCModule.Send(IIPCMessage message)
   at TVTComment.Model.ChatModule.CollectServiceModule_NewChatProduced(IEnumerable`1 newChats)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at TVTComment.App.Main()
```

**Comment by noriokun4649** [comment]
![image](https://user-images.githubusercontent.com/17977166/193417926-3441a96f-f099-48c0-adc8-ede1683c7d08.png)
TvTest 0.10.0 でチャンネル変更時にクラッシュしてたのと同じ箇所で、データがぶっ壊れてた
多分起動時と、番組切り替わりが重なって録画対象の番組情報がうまく取れてなさそう

**Comment by noriokun4649** [comment]
多分治った
